name = "RipRep"
authors = ["Laurence Sebastian Bowes"]

[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
OffsetArrays = "6fe1bfb0-de20-5000-8ca7-80f57d26f881"

[compat]
DrWatson = "2.9.1"
julia = "1.7.3"
